<?php \Theme::instance()->asset->css(array('docs.css'), array(), 'header'); ?>

<div id="docs">
	<div class="header">
		<div class="alignleft">
			<h1>Class API Documentation</h1>
		</div>
		<div class="alignright">
			<?php echo \Form::open(array('name' => 'version_select', 'action' => '/', 'method' => 'post'));?>
				<h5 style="margin-bottom:0px;">FuelPHP version: </h5>
				<?php echo \Form::select('branch', $selection['version'], $versions, array('style' => 'min-width:125px;', 'onchange' => 'this.form.action = this.form.action + \'/api/version/\' + this.value; this.form.submit();')); ?>
			<?php echo \Form::close(); ?>
		</div>
	</div>

	<div class="content">

		<div class="sidebar">

			<ul>
				<li>
					<button class="btn small expand_all">Expand All</button>
					<button class="btn small collapse_all">Collapse All</button>
				</li>
			</ul>

			<div id="menu_list">
				<h5>Constants</h5>
				<?php echo $constantlist; ?>

				<h5>Functions</h5>
				<?php echo $functionlist; ?>

				<h5>Classes</h5>
				<?php echo $classlist; ?>
			</div>

		</div>

		<div class="page">
			<div class="details">
				<?php echo $details; ?>
			</div>
		</div>
		<div class="clearfix"></div>

	</div>

	<div class="footer">
		<div class="center tiny">API documentation generated by <a href="http://www.docblox-project.org">Docblox</a> v0.18.1</div>
	</div>

</div>

<?php \Theme::instance()->asset->js(array('jquery.cooki.js'), array(), 'footer'); ?>
