<?php \Theme::instance()->asset->css(array('docs.css'), array(), 'header'); ?>

<div id="docs">
	<div class="header">
		<div class="alignleft">
			<h1>Class API Documentation</h1>
		</div>
		<div class="alignright">
			<form name="version_select" method="POST">
				<h5 style="margin-bottom:0px;">FuelPHP version: </h5>
				<?php echo \Form::select('branch', $selection['version'], $versions, array('style' => 'min-width:125px;', 'onchange' => 'this.form.action = this.form.action + \'/api/version/\' + this.value; this.form.submit();')); ?>
			</form>
		</div>
	</div>

	<div class="content">

		<div class="sidebar">
			<ul class="menutree">
				<li>
					<button class="btn small expand_all">Expand All</button>
					<button class="btn small collapse_all">Collapse All</button>
				</li>
			</ul>

			<h5>Constants</h5>
			<?php echo \Html::ul($constantlist, array('id' => 'constantlist', 'class' => 'menutree')); ?>

			<h5>Functions</h5>
			<?php echo \Html::ul($functionlist, array('id' => 'functionlist', 'class' => 'menutree')); ?>

			<h5>Classes</h5>
			<?php echo \Html::ul($classlist, array('id' => 'classlist', 'class' => 'menutree')); ?>
		</div>

		<div class="page">
			<div class="details">
				<?php echo $details; ?>
			</div>
		</div>
		<div class="clearfix"></div>

	</div>

	<div class="footer">
		<div class="center tiny">API documentation generated by <a href="http://www.docblox-project.org">Docblox</a> v0.18.1</div>
	</div>

</div>
